apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:17.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
              name: postgres
          env:
            - name: PGDATA
              value: /postgres/data
          volumeMounts:
            - name: postgres-mount
              mountPath: /postgres
      volumes:
        - name: postgres-mount
          hostPath:
            path: { { $.Values.storage.postgres.hostPath } }
